### PR TITLE
vendor: Bump Kubernetes dependencies to 1.20.2

### PR DESCRIPTION
**Pull request by adamwg**

### CODE REVIEW

**Comment by timoreimann** [comment]
Looks like some unit tests are failing due to what seems to be breaking changes in upstream.

**Comment by adamwg** [comment]
@timoreimann I believe I've fixed all the tests now (they're passing for me locally, anyway). Added the fixes in separate commits for easier review - PTAL!

**Review by timoreimann — APPROVED** [review]
LGTM, thanks. A quick update to the change log would be appreciated.

:shipit: on 🍏

**Comment by adamwg** [comment]
This is passing tests on 1.20 - merging now and then I'll cut a release.

**Pull request merged**
